#!/bin/bash

ps -ewwf

. /etc/default/scylla-server

echo "commandline------"
echo $@
echo "-------"
echo "environment------"
env | sort
echo "-------"

# TODO this couples too tightly to kubernetes service set convention -- move this up a level...
ID=$(echo $MY_POD_NAME | awk -F'-' '{print $NF}')
if [ -z "$ID" ]; then
    ID=0
fi

# generate seeds based on a range of seeds below me
# TODO This should be a bit sparse (taking into account AZs, etc)
COUNTER=0
SCYLLA_SEEDS=
while [ $COUNTER -lt $ID ]; do
    if [ x"$SCYLLA_SEEDS" != "x" ]; then
        SCYLLA_SEEDS+=,
    fi
    SCYLLA_SEEDS+=$MY_STATEFULSET_NAME-$COUNTER.$MY_STATEFULSET_NAME
    let COUNTER+=1
done

if [[ -n $SCYLLA_LISTEN_DEVICE ]]
then
	echo "SCYLLA_LISTEN_DEVICE was pre-set via environment to: $SCYLLA_LISTEN_DEVICE. Getting IP of device..."
	DEVICE_IP=$(ip -4 a show eth0 | awk '/inet /{ gsub(/\/[0-9]*/, "", $2); print $2 }')

	if [ $? -eq 0 ]
	then
		echo "IP sucessfully retrieved. Setting $DEVICE_IP as SCYLLA_LISTEN_ADDRESS."
		SCYLLA_LISTEN_ADDRESS=$DEVICE_IP
	else
		echo "IP of device could not be retrieved! Not setting SCYLLA_LISTEN_ADDRESS."
	fi
fi

if [[ -z $SCYLLA_LISTEN_ADDRESS ]]
then
	SCYLLA_LISTEN_ADDRESS=$(hostname -i)
	echo "SCYLLA_LISTEN_ADDRESS was dynamically set to 'hostname -i' address: $SCYLLA_LISTEN_ADDRESS"
else
	echo "SCYLLA_LISTEN_ADDRESS was pre-set via environment to: $SCYLLA_LISTEN_ADDRESS"
	if [[ $SCYLLA_LISTEN_ADDRESS =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
	then
		echo "SCYLLA_LISTEN_ADDRESS appears to be a valid IP address, moving on."
	else
		echo "SCYLLA_LISTEN_ADDRESS does not appear to be a valid IP address, trying to resolve..."
		RESOLVED_IP=$(host $SCYLLA_LISTEN_ADDRESS)

		if [ $? -eq 0 ]
		then
			SCYLLA_LISTEN_ADDRESS=$(echo $RESOLVED_IP | awk '{ print $4 }')
			echo "Resolved SCYLLA_LISTEN_ADDRESS to $SCYLLA_LISTEN_ADDRESS."
		else
			echo "Could not successfully resolve SCYLLA_LISTEN_ADDRESS, continuing."
		fi
	fi
fi

if [ x"$SCYLLA_SEEDS" != "x" ];then
	SEEDS="$SCYLLA_SEEDS"
else
	SEEDS="$SCYLLA_LISTEN_ADDRESS"
fi

sed -i "s/seeds: \"127.0.0.1\"/seeds: \"$SEEDS\"/g" /etc/scylla/scylla.yaml
sed -i "s/listen_address: localhost/listen_address: $SCYLLA_LISTEN_ADDRESS/g" /etc/scylla/scylla.yaml

if [ x"$SCYLLA_BROADCAST_ADDRESS" != "x" ];then
	sed -i "s/.*broadcast_address:.*/broadcast_address: $SCYLLA_BROADCAST_ADDRESS/g" /etc/scylla/scylla.yaml
fi

export SCYLLA_HOME SCYLLA_CONF

/usr/bin/scylla $@ --options-file /etc/scylla/scylla.yaml --listen-address $SCYLLA_LISTEN_ADDRESS --rpc-address $SCYLLA_LISTEN_ADDRESS --network-stack posix &

source /etc/default/scylla-jmx
export SCYLLA_HOME SCYLLA_CONF
exec /usr/lib/scylla/jmx/scylla-jmx -l /usr/lib/scylla/jmx &

wait