# rancher on OS configuration

replicaCount: 6

persistence:
  size: 10Ti
  storageClass: default

scylladb:
  config:
    overprovisioned: 0
    cpu: 8
    memory: 8G
    endpointSnitch: SimpleSnitch

  resources:
    requests:
      cpu: 8000m
      memory: 8Gi

kairosdb:

  datastoreReplicationFactor: 3

  queueProcessor: org.kairosdb.core.queue.MemoryQueueProcessor
  defaultTtl: "259200"
  memoryQueueSize: "5000000"

  service:
    type: LoadBalancer
    externalPort: 80

  resources:
    requests:
      cpu: 4000m
      memory: 4Gi

global:
  image:
    pullPolicy: Always
